version: '3'
services:
  nginx:
    image: kiambotehun/kss:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    environment:
      SERVER_NAME: example.org # to edit
      CERT_FULLCHAIN: cert_fullchain
      CERT_PRIVATEKEY: cert_privatekey